---
- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system
  become: true
  tags: flatpak,repositories

- name: Install Flathub packages
  community.general.flatpak:
    name: "{{ packages['flathub'] }}"
    remote: flathub
    state: present
    method: system
  when: packages['flathub'] is defined
  become: true
  tags: flatpak,packages