---
- name: Copy configuration files
  ansible.builtin.copy:
    src: .config
    dest: "/home/{{ ansible_user_id }}/.config"
  tags: dotfiles

- name: Copy Bash settings
  ansible.builtin.copy:
    src: .bashrc.d
    dest: "/home/{{ ansible_user_id }}"
  tags: dotfiles