---
- name: Install RPM Fusion repository
  ansible.builtin.import_tasks: set_rpmfusion_repo.yml
  become: true
  tags: packages,rpmfusion

- name: Install VSCode repository
  ansible.builtin.import_tasks: set_vscode_repo.yml
  become: true
  tags: packages,vscode

- name: Add Copr repositories
  community.general.copr:
    state: enabled
    name: "{{ item }}"
  loop: "{{ copr_repositories }}"
  when: copr_repositories is defined
  become: true
  tags: packages,copr

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ rpm_packages }}"
    state: present
    skip_broken: true
    allowerasing: true
  when: rpm_packages is defined
  become: true
  tags: packages,install