---
- name: Install RPM Fusion repository
  ansible.builtin.import_tasks: set_rpmfusion_repo.yml
  become: true
  tags: rpm,rpmfusion,repo

- name: Install VSCode repository
  ansible.builtin.import_tasks: set_vscode_repo.yml
  become: true
  tags: rpm,vscode,repo

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages['rpm'] }}"
    state: present
    skip_broken: true
    allowerasing: true
  when: packages['rpm'] is defined
  become: true
  tags: rpm,packages