---
- name: Copy configuration files
  ansible.builtin.copy:
    src: .config
    dest: "{{ ansible_env.HOME }}/.config"
  tags: dotfiles

- name: Copy Bash settings
  ansible.builtin.copy:
    src: .bashrc.d
    dest: "{{ ansible_env.HOME }}"
  tags: dotfiles