---
- name: Install RPM Fusion repository
  ansible.builtin.import_tasks: set_rpmfusion_repo.yml
  become: true
  tags: applications,rpmfusion

- name: Install VSCode repository
  ansible.builtin.import_tasks: set_vscode_repo.yml
  become: true
  tags: applications,vscode

- name: Install Flatpak applications
  ansible.builtin.import_tasks: install_flatpak.yml
  become: true
  tags: applications,flatpak

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages['rpm'] }}"
    state: present
    skip_broken: true
    allowerasing: true
  when: packages['rpm'] is defined
  become: true
  tags: applications,packages