---
- name: Set hostname
  ansible.builtin.copy:
    dest: /etc/hostname
    content: "{{ hostname }}"
  become: true
  tags: system,hostname

- name: Add realtime group to current user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: realtime
    append: yes
  become: true
  tags: system,audio