---
- name: Enable user services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services['system'] }}"
  when: services['system'] is defined
  become: true
  tags: systemd,services

- name: Enable user services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ services['user'] }}"
  when: services['user'] is defined
  tags: systemd,services