---
- name: Download Fira Code
  ansible.builtin.get_url:
    url: https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
    dest: /tmp/Fira_Code.zip

- name: ensure font dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/fira-code"
    recurse: true
    state: directory

- name: Extract Fira Code Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/Fira_Code.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/fira-code"

- name: Clean /tmp from Fira Code
  ansible.builtin.file:
    path: /tmp/Fira_Code.zip
    state: absent