---
- name: Configure Dconf settings
  ansible.builtin.import_tasks: configure_dconf.yml
  tags: user,dconf

- name: Copy dotfiles
  ansible.builtin.import_tasks: copy_dotfiles.yml
  tags: user,dotfiles